export interface Country {
  code: string;
  name: string;
}

// ISO 3166-1 alpha-2. Italia first, poi UE/EEA, poi alfabetico.
export const COUNTRIES: Country[] = [
  { code: 'IT', name: 'Italia' },
  { code: 'AT', name: 'Austria' },
  { code: 'BE', name: 'Belgio' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'CY', name: 'Cipro' },
  { code: 'HR', name: 'Croazia' },
  { code: 'DK', name: 'Danimarca' },
  { code: 'EE', name: 'Estonia' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'FR', name: 'Francia' },
  { code: 'DE', name: 'Germania' },
  { code: 'GR', name: 'Grecia' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'LV', name: 'Lettonia' },
  { code: 'LT', name: 'Lituania' },
  { code: 'LU', name: 'Lussemburgo' },
  { code: 'MT', name: 'Malta' },
  { code: 'NL', name: 'Paesi Bassi' },
  { code: 'PL', name: 'Polonia' },
  { code: 'PT', name: 'Portogallo' },
  { code: 'CZ', name: 'Repubblica Ceca' },
  { code: 'RO', name: 'Romania' },
  { code: 'SK', name: 'Slovacchia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'ES', name: 'Spagna' },
  { code: 'SE', name: 'Svezia' },
  { code: 'HU', name: 'Ungheria' },
  { code: 'IS', name: 'Islanda' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'NO', name: 'Norvegia' },
  { code: 'CH', name: 'Svizzera' },
  { code: 'GB', name: 'Regno Unito' },
  { code: 'AL', name: 'Albania' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AU', name: 'Australia' },
  { code: 'BR', name: 'Brasile' },
  { code: 'CA', name: 'Canada' },
  { code: 'CN', name: 'Cina' },
  { code: 'EG', name: 'Egitto' },
  { code: 'AE', name: 'Emirati Arabi Uniti' },
  { code: 'IN', name: 'India' },
  { code: 'JP', name: 'Giappone' },
  { code: 'IL', name: 'Israele' },
  { code: 'MX', name: 'Messico' },
  { code: 'MA', name: 'Marocco' },
  { code: 'NZ', name: 'Nuova Zelanda' },
  { code: 'RU', name: 'Federazione Russa' },
  { code: 'SA', name: 'Arabia Saudita' },
  { code: 'SG', name: 'Singapore' },
  { code: 'ZA', name: 'Sud Africa' },
  { code: 'KR', name: 'Corea del Sud' },
  { code: 'TR', name: 'Turchia' },
  { code: 'UA', name: 'Ucraina' },
  { code: 'US', name: 'Stati Uniti' },
  { code: 'VA', name: 'Città del Vaticano' },
  { code: 'SM', name: 'San Marino' },
];

const COUNTRY_CODES = new Set(COUNTRIES.map((c) => c.code));
export const isValidCountryCode = (v: string) => COUNTRY_CODES.has(v);
