/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppProfiloRouteImport } from './routes/app/profilo'
import { Route as AppImpostazioniRouteImport } from './routes/app/impostazioni'
import { Route as AppContattiRouteImport } from './routes/app/contatti'
import { Route as AppCertificatiRouteImport } from './routes/app/certificati'
import { Route as AppCategorieRouteImport } from './routes/app/categorie'
import { Route as AdminTipologieCertificatiRouteImport } from './routes/admin/tipologie-certificati'
import { Route as AdminSmtpRouteImport } from './routes/admin/smtp'
import { Route as AdminScadenzeRouteImport } from './routes/admin/scadenze'
import { Route as AdminFornitoriPendingRouteImport } from './routes/admin/fornitori-pending'
import { Route as AdminCategorieRouteImport } from './routes/admin/categorie'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminFornitoriIdRouteImport } from './routes/admin/fornitori.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppProfiloRoute = AppProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImpostazioniRoute = AppImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContattiRoute = AppContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCertificatiRoute = AppCertificatiRouteImport.update({
  id: '/certificati',
  path: '/certificati',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategorieRoute = AppCategorieRouteImport.update({
  id: '/categorie',
  path: '/categorie',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminTipologieCertificatiRoute =
  AdminTipologieCertificatiRouteImport.update({
    id: '/tipologie-certificati',
    path: '/tipologie-certificati',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSmtpRoute = AdminSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScadenzeRoute = AdminScadenzeRouteImport.update({
  id: '/scadenze',
  path: '/scadenze',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFornitoriPendingRoute = AdminFornitoriPendingRouteImport.update({
  id: '/fornitori-pending',
  path: '/fornitori-pending',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategorieRoute = AdminCategorieRouteImport.update({
  id: '/categorie',
  path: '/categorie',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFornitoriIdRoute = AdminFornitoriIdRouteImport.update({
  id: '/fornitori/$id',
  path: '/fornitori/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categorie': typeof AdminCategorieRoute
  '/admin/fornitori-pending': typeof AdminFornitoriPendingRoute
  '/admin/scadenze': typeof AdminScadenzeRoute
  '/admin/smtp': typeof AdminSmtpRoute
  '/admin/tipologie-certificati': typeof AdminTipologieCertificatiRoute
  '/app/categorie': typeof AppCategorieRoute
  '/app/certificati': typeof AppCertificatiRoute
  '/app/contatti': typeof AppContattiRoute
  '/app/impostazioni': typeof AppImpostazioniRoute
  '/app/profilo': typeof AppProfiloRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/fornitori/$id': typeof AdminFornitoriIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categorie': typeof AdminCategorieRoute
  '/admin/fornitori-pending': typeof AdminFornitoriPendingRoute
  '/admin/scadenze': typeof AdminScadenzeRoute
  '/admin/smtp': typeof AdminSmtpRoute
  '/admin/tipologie-certificati': typeof AdminTipologieCertificatiRoute
  '/app/categorie': typeof AppCategorieRoute
  '/app/certificati': typeof AppCertificatiRoute
  '/app/contatti': typeof AppContattiRoute
  '/app/impostazioni': typeof AppImpostazioniRoute
  '/app/profilo': typeof AppProfiloRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/fornitori/$id': typeof AdminFornitoriIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categorie': typeof AdminCategorieRoute
  '/admin/fornitori-pending': typeof AdminFornitoriPendingRoute
  '/admin/scadenze': typeof AdminScadenzeRoute
  '/admin/smtp': typeof AdminSmtpRoute
  '/admin/tipologie-certificati': typeof AdminTipologieCertificatiRoute
  '/app/categorie': typeof AppCategorieRoute
  '/app/certificati': typeof AppCertificatiRoute
  '/app/contatti': typeof AppContattiRoute
  '/app/impostazioni': typeof AppImpostazioniRoute
  '/app/profilo': typeof AppProfiloRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/fornitori/$id': typeof AdminFornitoriIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/categorie'
    | '/admin/fornitori-pending'
    | '/admin/scadenze'
    | '/admin/smtp'
    | '/admin/tipologie-certificati'
    | '/app/categorie'
    | '/app/certificati'
    | '/app/contatti'
    | '/app/impostazioni'
    | '/app/profilo'
    | '/admin/'
    | '/app/'
    | '/admin/fornitori/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/categorie'
    | '/admin/fornitori-pending'
    | '/admin/scadenze'
    | '/admin/smtp'
    | '/admin/tipologie-certificati'
    | '/app/categorie'
    | '/app/certificati'
    | '/app/contatti'
    | '/app/impostazioni'
    | '/app/profilo'
    | '/admin'
    | '/app'
    | '/admin/fornitori/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/categorie'
    | '/admin/fornitori-pending'
    | '/admin/scadenze'
    | '/admin/smtp'
    | '/admin/tipologie-certificati'
    | '/app/categorie'
    | '/app/certificati'
    | '/app/contatti'
    | '/app/impostazioni'
    | '/app/profilo'
    | '/admin/'
    | '/app/'
    | '/admin/fornitori/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/profilo': {
      id: '/app/profilo'
      path: '/profilo'
      fullPath: '/app/profilo'
      preLoaderRoute: typeof AppProfiloRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/impostazioni': {
      id: '/app/impostazioni'
      path: '/impostazioni'
      fullPath: '/app/impostazioni'
      preLoaderRoute: typeof AppImpostazioniRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contatti': {
      id: '/app/contatti'
      path: '/contatti'
      fullPath: '/app/contatti'
      preLoaderRoute: typeof AppContattiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/certificati': {
      id: '/app/certificati'
      path: '/certificati'
      fullPath: '/app/certificati'
      preLoaderRoute: typeof AppCertificatiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/categorie': {
      id: '/app/categorie'
      path: '/categorie'
      fullPath: '/app/categorie'
      preLoaderRoute: typeof AppCategorieRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/tipologie-certificati': {
      id: '/admin/tipologie-certificati'
      path: '/tipologie-certificati'
      fullPath: '/admin/tipologie-certificati'
      preLoaderRoute: typeof AdminTipologieCertificatiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/smtp': {
      id: '/admin/smtp'
      path: '/smtp'
      fullPath: '/admin/smtp'
      preLoaderRoute: typeof AdminSmtpRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scadenze': {
      id: '/admin/scadenze'
      path: '/scadenze'
      fullPath: '/admin/scadenze'
      preLoaderRoute: typeof AdminScadenzeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fornitori-pending': {
      id: '/admin/fornitori-pending'
      path: '/fornitori-pending'
      fullPath: '/admin/fornitori-pending'
      preLoaderRoute: typeof AdminFornitoriPendingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categorie': {
      id: '/admin/categorie'
      path: '/categorie'
      fullPath: '/admin/categorie'
      preLoaderRoute: typeof AdminCategorieRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fornitori/$id': {
      id: '/admin/fornitori/$id'
      path: '/fornitori/$id'
      fullPath: '/admin/fornitori/$id'
      preLoaderRoute: typeof AdminFornitoriIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategorieRoute: typeof AdminCategorieRoute
  AdminFornitoriPendingRoute: typeof AdminFornitoriPendingRoute
  AdminScadenzeRoute: typeof AdminScadenzeRoute
  AdminSmtpRoute: typeof AdminSmtpRoute
  AdminTipologieCertificatiRoute: typeof AdminTipologieCertificatiRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFornitoriIdRoute: typeof AdminFornitoriIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCategorieRoute: AdminCategorieRoute,
  AdminFornitoriPendingRoute: AdminFornitoriPendingRoute,
  AdminScadenzeRoute: AdminScadenzeRoute,
  AdminSmtpRoute: AdminSmtpRoute,
  AdminTipologieCertificatiRoute: AdminTipologieCertificatiRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFornitoriIdRoute: AdminFornitoriIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppCategorieRoute: typeof AppCategorieRoute
  AppCertificatiRoute: typeof AppCertificatiRoute
  AppContattiRoute: typeof AppContattiRoute
  AppImpostazioniRoute: typeof AppImpostazioniRoute
  AppProfiloRoute: typeof AppProfiloRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCategorieRoute: AppCategorieRoute,
  AppCertificatiRoute: AppCertificatiRoute,
  AppContattiRoute: AppContattiRoute,
  AppImpostazioniRoute: AppImpostazioniRoute,
  AppProfiloRoute: AppProfiloRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
