export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_SUPPLIER_NOT_APPROVED: 'AUTH_SUPPLIER_NOT_APPROVED',
  AUTH_USER_DISABLED: 'AUTH_USER_DISABLED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REUSED: 'AUTH_TOKEN_REUSED',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PIVA_ALREADY_REGISTERED: 'PIVA_ALREADY_REGISTERED',
  CF_ALREADY_REGISTERED: 'CF_ALREADY_REGISTERED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RLS_FORBIDDEN: 'RLS_FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
